const TokenizeIT = artifacts.require('TokenizeIT');
const Processor = artifacts.require('Processor');
const Dividends = artifacts.require('Dividends');
//const AuctionFractionalizer = artifacts.require('AuctionFractionalizer');
//const AuctionTips = artifacts.require('AuctionTips');
const AuctionTipsImpl = artifacts.require('AuctionTipsImpl');
//const CollectivePurchase = artifacts.require('CollectivePurchase');
const Fractionalizer = artifacts.require('Fractionalizer');
//const Tips = artifacts.require('Tips');
const TipsImpl = artifacts.require('TipsImpl');
const SafeERC721 = artifacts.require('SafeERC721Metadata');
const SafeERC721Metadata = artifacts.require('SafeERC721Metadata');

module.exports = async (deployer, network, [account]) => {
  await deployer.deploy(SafeERC721Metadata);
  deployer.link(SafeERC721Metadata, Processor);
  await deployer.deploy(Processor);
  deployer.link(SafeERC721Metadata, Dividends);
  await deployer.deploy(Dividends);
  //deployer.link(SafeERC721Metadata, AuctionFractionalizer);
  //await deployer.deploy(AuctionFractionalizer);
  //deployer.link(SafeERC721Metadata, AuctionTips);
  //await deployer.deploy(AuctionTips);
  deployer.link(SafeERC721Metadata, AuctionTipsImpl);
  await deployer.deploy(AuctionTipsImpl);
  //deployer.link(SafeERC721Metadata, CollectivePurchase);
  //await deployer.deploy(CollectivePurchase);
  deployer.link(SafeERC721Metadata, Fractionalizer);
  await deployer.deploy(Fractionalizer);
  //deployer.link(SafeERC721Metadata, Tips);
  //await deployer.deploy(Tips);
  deployer.link(SafeERC721Metadata, TipsImpl);
  await deployer.deploy(TipsImpl);
  deployer.link(SafeERC721Metadata, SafeERC721);
  await deployer.deploy(SafeERC721);
  deployer.link(Processor, TokenizeIT);
  deployer.link(Dividends, TokenizeIT);
  //deployer.link(AuctionFractionalizer, TokenizeIT);
  //deployer.link(AuctionTips, TokenizeIT);
  deployer.link(AuctionTipsImpl, TokenizeIT);
  //deployer.link(CollectivePurchase, TokenizeIT);
  deployer.link(Fractionalizer, TokenizeIT);
  //deployer.link(Tips, TokenizeIT);
  deployer.link(TipsImpl, TokenizeIT);
  deployer.link(SafeERC721, TokenizeIT);
  await deployer.deploy(TokenizeIT);
};
